<?php
include 'database.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['consumer_id'])) {
    $consumerId = intval($_POST['consumer_id']);

    // Updated SQL query to fetch the most recent record for the current month
    $sql = "
        SELECT 
            c.account_number, 
            c.name, 
            em.meter_id,
            dc.energy_consumed AS recent_consumption,
            (dc.energy_consmed * 6) AS monthly_consumption,
            (dc.energy_consumed * 30 * 6) AS total_pay,
            dc.date AS bill_date
        FROM 
            consumers c
        LEFT JOIN 
            electricitymeters em ON c.consumer_id = em.consumer_id
        LEFT JOIN 
            consumption_records dc ON c.consumer_id = dc.consumer_id
        WHERE 
            c.consumer_id = $consumerId 
        AND 
            MONTH(dc.date) = MONTH(CURDATE()) 
        AND 
            YEAR(dc.date) = YEAR(CURDATE())
        ORDER BY 
            dc.date DESC
        LIMIT 1
    ";

    $result = mysqli_query($conn, $sql);

    if ($result && $row = mysqli_fetch_assoc($result)) {
        echo "
        <h2>Monthly Pay Receipt</h2>
        <p><strong>Account Number:</strong> {$row['account_number']}</p>
        <p><strong>Consumer Name:</strong> {$row['name']}</p>
        <p><strong>Meter ID:</strong> {$row['meter_id']}</p>
        <p><strong>Bill Date:</strong> {$row['bill_date']}</p>
        <p><strong>Monthly Consumption:</strong> {$row['monthly_consumption']} kWh</p>
        <p><strong>Total Pay:</strong> ₱{$row['total_pay']}</p>
        <p><strong>Generated By:</strong> {$row['name']}</p>
        <p><em>Date Generated:</em> " . date('Y-m-d') . "</p>
        ";
    } else {
        echo "<p>No records found for this consumer in the current month.</p>";
    }

    mysqli_close($conn);
} else {
    echo "<p>Invalid request.</p>";
}
?>
