<?php
include 'database.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['consumer_id'])) {
    $consumerId = intval($_POST['consumer_id']);

    $sql = "
        SELECT 
            c.account_number, 
            c.name, 
            em.meter_id,
            SUM(dc.energy_consumed) AS total_monthly_consumption,
            (SUM(dc.energy_consumed) * 6) AS total_pay
        FROM 
            consumers c
        LEFT JOIN 
            electricitymeters em ON c.consumer_id = em.consumer_id
        LEFT JOIN 
            consumption_records dc ON c.consumer_id = dc.consumer_id
        WHERE 
            c.consumer_id = $consumerId 
        AND 
            MONTH(dc.date) = MONTH(CURDATE()) 
        AND 
            YEAR(dc.date) = YEAR(CURDATE())
        GROUP BY 
            c.consumer_id
    ";

    $result = mysqli_query($conn, $sql);

    if ($result && $row = mysqli_fetch_assoc($result)) {
        echo "
        <h2>Monthly Pay Receipt</h2>
        <p><strong>Account Number:</strong> {$row['account_number']}</p>
        <p><strong>Consumer Name:</strong> {$row['name']}</p>
        <p><strong>Meter ID:</strong> {$row['meter_id']}</p>
        <p><strong>Total Monthly Consumption:</strong> {$row['total_monthly_consumption']} kWh</p>
        <p><strong>Total Pay:</strong> ₱{$row['total_pay']}</p>
        <p><strong>Generated By:</strong> {$row['name']}</p>
        <p><em>Date Generated:</em> " . date('Y-m-d') . "</p>
        ";
    } else {
        echo "<p>No records found for this consumer in the current month.</p>";
    }

    mysqli_close($conn);
} else {
    echo "<p>Invalid request.</p>";
}
?>
